# Adapted from https://gist.github.com/mrlesmithjr/f3c15fdd53020a71f55c2032b8be2eda
---
- name: Install packages
  hosts: localhost
  connection: local
  remote_user: akzn
  vars:
    brew_taps:
      - 'homebrew/cask-versions'
      - 'homebrew/cask-fonts'
    brew_casks:
      - 'firefox'
      - 'google-chrome'
      - 'iterm2'
      - 'lastpass'
      - 'spotify)'
      - 'vlc'
      - 'spectacle'
      - 'filezilla'
      - 'android-studio'
      - 'visual-studio-code'
      - 'java'
      - 'psequel'
      - 'aws-vault'
      - 'docker'
      - 'minikube'
      - 'simplenote'
      - 'vagrant'
      - 'vagrant-manager'
      - 'virtualbox'
      - 'virtualbox-extension-pack'
    brew_packages:
      - 'bash-completion'
      - 'wp-cli'
      - 'jq'
      - 'nmap'
      - 'nomad'
      - 'pipenv'
      - 'rbenv'
      - 'tfenv'
      - 'jenv'
      - 'tree'
      - 'wget'
      - 'tree'
      - 'htop'
      - 'awscli'
      - 'postgres'
      - 'ansible'
    upgrade: false
  
  pre-tasks:
    - name: Check if homebrew installed
      stat:
        path: "/usr/local/bin/brew"
        register: "homebrew_check"
      
    - name: Fail if homebrew not installed
      fail:
        msg: "Homebrew seems to be missing... exiting"
        when: not homebrew_check.stat.exists

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists
    
    - name: Installing taps
      homebrew_tap:
        name: "{{ brew_taps }}"
        state: present
        when: homebrew_check.stat.exists

    - name: Installing homebrew packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
        upgrade_all: "{{ upgrade }}"
        when: homebrew_check.stat.exists

    - name: Installing cask packages
      homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
        upgrade_all: "{{ upgrade }}"
        when: homebrew_check.stat.exists