---
- name: Installing cask packages
  homebrew_cask:
    name: "{{ brew_casks }}"
    state: present
    upgrade_all: "{{ upgrade }}"
    when: homebrew_check.stat.exists
  with_items: "{{ brew_casks }}"
  