---
# homebrew_cask throwing errors with using var in with_items; this is a workaround for now
- name: Installing cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: installed
    install_options: force  # Force install because brew cask fails when app already there
    upgrade_all: "{{ upgrade }}"
  when: homebrew_check.stat.exists
  with_items: 
    - 'firefox'
    - 'google-chrome'
    - 'iterm2'
    - 'lastpass'
    - 'spotify'
    - 'vlc'
    - 'itsycal'
    - 'spectacle'
    - 'android-studio'
    - 'visual-studio-code'
    - 'aws-vault'
    - 'simplenote'
    - 'whatsapp'
    - 'vagrant'
    - 'vagrant-manager'
    - 'virtualbox'
    - 'virtualbox-extension-pack'
    - 'notion'
    - 'discord'
    - 'intellij-idea-ce'
    - '1password'
    - 'cleanmymac'
    - 'coconutbattery'
    - 'microsoft-office'
    - 'nordvpn'
    - 'postman'
    - 'zoom'
    - 'adobe-acrobat-reader'
