---
- name: Check if homebrew installed
  stat:
    path: "/usr/local/bin/brew"
    register: "homebrew_check"
  
- name: Fail if homebrew not installed
  fail:
    msg: "Homebrew seems to be missing... exiting"
    when: not homebrew_check.stat.exists

- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists